### ISSUE TITLE
进行onnxsim转换后，还是会提示模型超过2GB

### ISSUE THREAD

**Issue by shanyuaa** [luchangli03/onnxsim_large_model#8]
<img width="755" alt="截屏2024-06-11 02 23 23" src="https://github.com/luchangli03/onnxsim_large_model/assets/54535300/20f2a5d1-518c-4b57-abe2-bffa190e76aa">

**Comment by luchangli03** [comment]
please try the new code

**Comment by shanyuaa** [comment]
你好，我已收到信件，在阅读后会尽快给回复。祝好。
